import { useState } from "react";
import { ConversionHero } from "../../design-system/patterns";
import { ModalityRail, type RouteData } from "../../design-system/components";
import { Button, Notice, SectionHeading } from "../../design-system/primitives";
import { InternationalTransfer, type Region } from "../../components/ui/country-accordion";
import { ScrollFlyIn } from "../../components/ui/hero-section-3";
import { FAQItem } from "../../components/ui/system";
import { ArrowRight, ClipboardCheck, Crown, FileText, Globe2, Headset, HeartHandshake, MapPin, Package, Plane, Route, ShieldCheck, Volume2, VolumeX } from "lucide-react";
import { SiteHeader } from "../../components/ui/navigation";
import { SiteFooter } from "../../components/ui/footer";
import { WhatsAppFloat, type LeadContext } from "../../components/ui/whatsapp-float";
import { HeroRouteStarter } from "../../components/ui/hero-route-starter";
import { CaseDragCards } from "../../components/ui/case-drag-cards";

const images = {
  planning: "/embarpet-trip-planning.png",
  crate: "/embarpet-crate-preparation.png",
  documents: "/embarpet-autoridade-destino-real.jpeg",
  service: "/embarpet-service-management.webp",
  luxury: "/embarpet-pet-luxo.png",
};

const teamMembers = [
  { name: "Fernando", role: "Atendimento inicial" }, { name: "Juliane", role: "Planejamento de rota" }, { name: "Kimberlie", role: "Documentação" }, { name: "Ystefani", role: "Operações" }, { name: "Luiz", role: "Atendimento" },
  { name: "Daiane", role: "Planejamento" }, { name: "Suzaine", role: "Documentação" }, { name: "Flora", role: "Operações" }, { name: "Igor", role: "Atendimento" }, { name: "Celida", role: "Planejamento" },
  { name: "Evelyn", role: "Documentação" }, { name: "Rafael", role: "Operações" }, { name: "Ednilton", role: "Atendimento" }, { name: "Thamires", role: "Planejamento" }, { name: "Elizabeth", role: "Operações" },
];

const regions: Region[] = [
  { id:"eua", label:"Estados Unidos", countries:[{ code:"us", name:"Estados Unidos" }] },
  { id:"ue", label:"União Europeia", countries:[{ code:"pt", name:"Portugal" },{ code:"es", name:"Espanha" },{ code:"it", name:"Itália" },{ code:"fr", name:"França" },{ code:"de", name:"Alemanha" },{ code:"nl", name:"Países Baixos" }] },
  { id:"mercosul", label:"Mercosul", countries:[{ code:"ar", name:"Argentina" },{ code:"uy", name:"Uruguai" },{ code:"py", name:"Paraguai" }] },
];

const embarkationGallery = [
  { src:"/embarpet-viagem-cabine.jpg", alt:"Pet em contexto de viagem na cabine", destination:"Estados Unidos" },
  { src:"/embarpet-bagagem-acompanhada.webp", alt:"Consultora Embarpet acompanhando pets no aeroporto", destination:"Portugal" },
  { src:"/embarpet-compartimento-cargas.jpg", alt:"Pet em caixa de transporte no processo operacional", destination:"Espanha" },
  { src:"/embarpet-pet-luxo-real.jpeg", alt:"Acompanhamento de pet em aeroporto", destination:"Itália" },
  { src:"/embarpet-mosaico-familia.jpg", alt:"Família em contexto de viagem com pet", destination:"Estados Unidos" },
  { src:"/embarpet-mosaico-cabine.jpeg", alt:"Pet viajando em cabine aérea", destination:"França" },
  { src:"/embarpet-mosaico-encontro.jpg", alt:"Encontro de família e pet após a jornada", destination:"Argentina" },
  { src:"/embarpet-carga-viva-operacao.jpeg", alt:"Operação de embarque internacional de pet", destination:"Uruguai" },
];

function EmbarkationMarquee() {
  const railItems = [...embarkationGallery, ...embarkationGallery];
  return <section className="ep-embarkation-marquee" aria-label="Embarques acompanhados pela Embarpet"><div className="ep-embarkation-marquee__viewport"><div className="ep-embarkation-marquee__track">{[0, 1].map((rail) => <div className="ep-embarkation-marquee__rail" key={rail} aria-hidden={rail ? "true" : undefined}>{railItems.map(({ src, alt, destination }, index) => <figure className="ep-embarkation-marquee__item" key={`${src}-${rail}-${index}`}><img src={src} alt={rail ? "" : alt} loading="lazy" decoding="async" /><figcaption><span>Brasil</span><Plane size={12} aria-hidden="true" /><b>{destination}</b></figcaption></figure>)}</div>)}</div></div></section>;
}

export default function EmbarpetHome() {
  const [route, setRoute] = useState<RouteData>({ origin:"", destination:"", period:"" });
  const [message, setMessage] = useState("");
  const [petLuxoUnmuted, setPetLuxoUnmuted] = useState(false);
  const [petLuxoFullVideoLoaded, setPetLuxoFullVideoLoaded] = useState(false);
  const [heroVideoUnmuted, setHeroVideoUnmuted] = useState(false);
  const [heroVideoFullLoaded, setHeroVideoFullLoaded] = useState(false);
  const startFromDestination = (destination: string) => {
    setRoute((current) => ({ ...current, destination }));
    document.getElementById("analise")?.scrollIntoView({ behavior:"smooth" });
  };
  const leadContext: LeadContext = { source:"home", page:"/", origin:route.origin, destination:route.destination, period:route.period };

  return <><SiteHeader overlay logoSrc="/logo-embarpet-dark.png" items={[
    { label:"Como funciona", href:"#como-funciona" },
    { label:"Modalidades", href:"#modalidades", children:[
      { label:"Viagem na cabine", href:"#modalidades", description:"Possibilidade para alguns pets e rotas.", icon:Plane },
      { label:"Bagagem acompanhada", href:"#modalidades", description:"Mesmo voo do tutor, em compartimento próprio.", icon:Package },
      { label:"Compartimento de cargas", href:"#modalidades", description:"Operação com estrutura própria para o pet.", icon:Route },
      { label:"Suporte emocional", href:"#modalidades", description:"Avaliação conforme rota e critérios vigentes.", icon:HeartHandshake },
    ] },
    { label:"Serviços", href:"#servicos" },
    { label:"Destinos", href:"#destinos", children:[
      { label:"Estados Unidos", href:"#destinos", description:"Planejamento da rota Brasil–EUA.", icon:Route },
      { label:"União Europeia", href:"#destinos", description:"Cada país pede leitura própria.", icon:Route },
      { label:"Mercosul", href:"#destinos", description:"Planejamento regional com atenção ao caso.", icon:Route },
    ] },
    { label:"Conteúdo", href:"#faq" },
  ]} /><main>
    <ConversionHero aside={<div className="ep-hero-video"><video key={heroVideoFullLoaded ? "hero-full" : "hero-preview"} poster="/embarpet-pet-luxo-real.jpeg" aria-label="Acompanhamento Embarpet em contexto de viagem" autoPlay loop muted={heroVideoFullLoaded ? !heroVideoUnmuted : true} playsInline preload="metadata">{!heroVideoFullLoaded ? <source src="/embarpet-petluxo-preview-5s.webm" type="video/webm" /> : null}<source src={heroVideoFullLoaded ? "/embarpet-petluxo-baeta-alpargata.mp4" : "/embarpet-petluxo-preview-5s.mp4"} type="video/mp4" /></video><button type="button" className="ep-hero-video__sound" onClick={() => { if (!heroVideoFullLoaded) { setHeroVideoFullLoaded(true); setHeroVideoUnmuted(true); return; } setHeroVideoUnmuted((current) => !current); }}>{heroVideoUnmuted ? <VolumeX size={15} /> : <Volume2 size={15} />}{heroVideoUnmuted ? "Silenciar" : "Ativar som"}</button></div>}>
      <h1 className="ep-title-xl">Seu <span className="ep-hero-highlight">pet vai para outro país?</span><span className="ep-hero-flags" aria-hidden="true"><img src="/apple-emoji/flag-br.png" alt="" /><img src="/apple-emoji/flag-us.png" alt="" /><img src="/apple-emoji/flag-pt.png" alt="" /><img src="/apple-emoji/flag-es.png" alt="" /><img src="/apple-emoji/flag-it.png" alt="" /></span></h1>
      <p className="ep-hero-route-intro">Responda em poucos passos e receba uma <strong>previsão personalizada</strong> para o embarque do seu pet.</p>
      <div className="ep-conversion-hero__form"><HeroRouteStarter /></div>
      <div className="ep-hero-proof" aria-label="Experiência e credenciais Embarpet"><div className="ep-hero-proof__metric"><span className="ep-team-avatars" aria-hidden="true"><i /><i /><i /><i /></span><strong>+2.000</strong><small>embarques<br />analisados</small></div><div className="ep-hero-proof__metric"><img src="https://www.gstatic.com/images/branding/searchlogo/ico/favicon.ico" alt="Google" /><strong>4,9</strong><small>avaliação<br />no Google</small></div><div className="ep-hero-proof__credential"><span><img src="/logo-ipata.png" alt="IPATA" /><img src="/logo-iata.png" alt="IATA" /></span><small>Credenciados</small></div><a className="ep-hero-proof__credential" href="https://www.reclameaqui.com.br/empresa/embarpet-embarque-de-animais/" target="_blank" rel="noreferrer"><img src="https://www.reclameaqui.com.br/favicon.ico" alt="Reclame Aqui" /><strong>0</strong><small>reclamações<br />no Reclame Aqui</small></a></div>
    </ConversionHero>
    {message ? <div className="ep-container ep-home-notice"><Notice kind="success">{message}</Notice></div> : null}
    <EmbarkationMarquee />

    <section className="ep-home-modalities" id="modalidades"><div className="ep-container"><div className="ep-home-modalities__intro"><div><p className="ep-eyebrow">Antes de escolher</p><h2 className="ep-title-lg">Antes da modalidade, vem a leitura do seu caso.</h2></div><p className="ep-copy">Destino, perfil do pet, companhia aérea e documentação definem qual alternativa pode fazer sentido para a viagem.</p></div>
      <ModalityRail items={[
        { icon:"plane", title:"Viagem na cabine", copy:"Em algumas rotas, pets dentro dos critérios podem viajar próximos ao tutor.", ctaLabel:"Avaliar possibilidade de cabine", detailHref:"/modalidades/viagem-na-cabine", imageSrc:"/embarpet-viagem-cabine.jpg", imageAlt:"Pet olhando pela janela durante um voo em cabine" },
        { icon:"document", title:"Bagagem acompanhada", copy:"Em determinados casos, o pet embarca no mesmo voo do tutor, em compartimento apropriado.", ctaLabel:"Avaliar bagagem acompanhada", detailHref:"/modalidades/bagagem-acompanhada", imageSrc:"/embarpet-bagagem-acompanhada.webp", imageAlt:"Consultora Embarpet acompanhando pets em aeroporto" },
        { icon:"home", title:"Compartimento de cargas", copy:"Uma operação especializada para perfis, rotas ou viagens que pedem uma estrutura própria.", ctaLabel:"Avaliar compartimento de cargas", detailHref:"/modalidades/compartimento-de-cargas", imageSrc:"/embarpet-compartimento-cargas.jpg", imageAlt:"Pet em caixa de transporte na esteira operacional do aeroporto", featured:true },
        { icon:"shield", title:"Suporte emocional", copy:"Em situações aplicáveis, avaliamos o contexto da viagem e os critérios da companhia aérea para orientar os próximos passos.", ctaLabel:"Avaliar suporte emocional", detailHref:"/modalidades/suporte-emocional", imageSrc:"/embarpet-suporte-emocional.jpg", imageAlt:"Família com pet em voo durante uma viagem" },
      ]} />
      <p className="ep-home-bridge">A melhor possibilidade nasce da análise certa — e é isso que começamos a fazer com você.</p>
    </div></section>

    <section className="ep-home-service" id="servicos"><div className="ep-container ep-home-service__grid"><figure className="ep-home-ceo" aria-label="Thamires Félix, da equipe Embarpet, com diferentes espécies de pets"><div className="ep-home-ceo__glow" aria-hidden="true" /><img src="/embarpet-ceo-equipe-trim.webp" alt="Thamires Félix com cachorro, gato, hamster, ave e tartaruga" /><span className="ep-home-ceo__fade" aria-hidden="true" /><figcaption>Thamires Félix <small>Embarpet</small></figcaption></figure><div><p className="ep-eyebrow">Quem cuida da viagem <span className="ep-home-service__client-portraits" aria-label="Histórias acompanhadas pela Embarpet"><img src="/case-leandro-hassum.jpeg" alt="Leandro Hassum" /><img src="/case-talles-magno.jpg" alt="Talles Magno" /><img src="/case-renato-paiva.jpeg" alt="Renato Paiva" /></span></p><h2 className="ep-title-lg">Autoridade se constrói em cada embarque.</h2><p className="ep-copy">Thamires Félix e uma equipe especializada conectam atendimento, documentação e operação para transformar uma viagem complexa em próximos passos claros.</p><div className="ep-home-service__media"><a href="https://revistapegn.globo.com/Mulheres-empreendedoras/fotos/2019/11/mulheres-empreendedoras-10-negocios-de-sucesso-liderados-por-mulheres.html" target="_blank" rel="noopener noreferrer" aria-label="Ler na PEGN Globo: empreendedorismo feminino e o crescimento da Embarpet"><b className="ep-media-logo ep-media-logo--pegn">PEGN <i>/ Globo</i></b><strong>Empreendedorismo feminino e o crescimento da Embarpet.</strong><span>Ler matéria <ArrowRight size={13} /></span></a><a href="https://catracalivre.com.br/viagem-livre/conheca-as-regras-para-viajar-de-aviao-com-animais-exoticos/" target="_blank" rel="noopener noreferrer" aria-label="Ler na Catraca Livre: regras para viajar de avião com animais exóticos"><b className="ep-media-logo ep-media-logo--catraca">Catraca Livre</b><strong>Regras para viajar de avião com animais exóticos.</strong><span>Ler matéria <ArrowRight size={13} /></span></a><a href="https://visitebrasilia.com.br/noticias/pet-nas-alturas-entenda-como-funcionam-os-tipos-de-embarque-e-qual-o-melhor-para-o-seu-animal-de-estimacao" target="_blank" rel="noopener noreferrer" aria-label="Ler no Visite Brasília: tipos de embarque para pets"><b className="ep-media-logo ep-media-logo--visite">Visite Brasília</b><strong>Tipos de embarque para pets explicados por quem opera.</strong><span>Ler matéria <ArrowRight size={13} /></span></a></div><a className="ep-button ep-button--secondary" href="/equipe-e-credenciais"><span>Conhecer quem faz a Embarpet</span><ArrowRight size={18} aria-hidden="true" /></a></div></div></section>

    <section className="ep-home-process-section" id="como-funciona"><div className="ep-container ep-home-process ep-home-process--cycle"><div className="ep-home-process__intro"><p className="ep-eyebrow">Nosso processo</p><h2 className="ep-title-lg">Transformamos complexidade em <em>caminho.</em></h2><p className="ep-copy">Conectamos rota, perfil do pet, exigências e operação para que cada decisão tenha contexto antes de virar próximo passo.</p><a className="ep-home-process__cta" href="#analise"><span>Começar minha análise</span><ArrowRight size={18} aria-hidden="true" /></a></div><div className="ep-home-process__cycle" aria-label="As quatro etapas da metodologia Embarpet"><span className="ep-home-process__orbit" aria-hidden="true" /><div className="ep-home-process__core"><img src="/logo-embarpet-symbol.png" alt="" /><strong>Método<br />Embarpet</strong><small>Uma jornada<br />com contexto.</small></div>{[
      { icon:Globe2, title:"Entendemos a viagem", copy:"Origem, destino, prazo e o perfil do pet.", number:"01" },
      { icon:ClipboardCheck, title:"Desenhamos o plano", copy:"Possibilidades e cronograma para a família.", number:"02" },
      { icon:FileText, title:"Preparamos as etapas", copy:"Documentação e orientações do seu caso.", number:"03" },
      { icon:Headset, title:"Acompanhamos a operação", copy:"Marcos definidos até o próximo encontro.", number:"04" },
    ].map(({ icon: Icon, title, copy, number }, index) => <span className="ep-home-process__satellite" key={title} style={{ "--ep-orbit-angle": `${index * 90}deg` } as React.CSSProperties}><a className="ep-home-process__cycle-step" href="#analise"><span className="ep-home-process__cycle-icon"><Icon size={20} strokeWidth={1.7} /></span><span><b>{number}</b><strong>{title}</strong><small>{copy}</small></span></a></span>)}</div></div></section>

    <section className="ep-home-cases" id="historias"><CaseDragCards cases={[
      { id:"leandro-hassum", title:"Leandro Hassum", subtitle:"Brasil → Estados Unidos", instagramHandle:"@leandrohassum", instagramUrl:"https://www.instagram.com/leandrohassum/", imageSrc:"/case-leandro-hassum.jpeg", imageAlt:"Leandro Hassum e equipe Embarpet no aeroporto" },
      { id:"talles-magno", title:"Talles Magno", subtitle:"Brasil → Estados Unidos", instagramHandle:"@talles_magno", instagramUrl:"https://www.instagram.com/talles_magno/", imageSrc:"/case-talles-magno.jpg", imageAlt:"Tutor com pet em Nova York" },
      { id:"alan-franco", title:"Alan Franco", subtitle:"Brasil → Estados Unidos", instagramHandle:"@alanfranco_", instagramUrl:"https://www.instagram.com/alanfranco_/", imageSrc:images.documents, imageAlt:"Documentação para viagem com pet" },
      { id:"kiliquinha", title:"Kiliquinha", subtitle:"Brasil → Estados Unidos", instagramHandle:"@kiliquinha", instagramUrl:"https://www.instagram.com/kiliquinha/", imageSrc:images.service, videoSrc:"/case-kiliquinha-preview-5s.mp4", previewWebmSrc:"/case-kiliquinha-preview-5s.webm", fullVideoSrc:"/case-kiliquinha.mp4", imageAlt:"Vídeo da Kiliquinha em contexto de viagem" },
      { id:"renato-paiva", title:"Renato Paiva", subtitle:"Jornada internacional com a Embarpet", instagramHandle:"@renatopaiva009", instagramUrl:"https://www.instagram.com/renatopaiva009/", imageSrc:"/case-renato-paiva.jpeg", imageAlt:"Renato Paiva com a equipe Embarpet" },
    ]} /></section>

    <section className="ep-home-luxury" id="pet-luxo"><div className="ep-container ep-home-luxury__grid"><div className="ep-home-luxury__image"><video key={petLuxoFullVideoLoaded ? "petluxo-full" : "petluxo-preview"} poster="/embarpet-pet-luxo-real.jpeg" aria-label="Consultora Embarpet acompanhando pets no aeroporto" autoPlay loop muted={petLuxoFullVideoLoaded ? !petLuxoUnmuted : true} playsInline preload="metadata">{!petLuxoFullVideoLoaded ? <source src="/embarpet-petluxo-preview-5s.webm" type="video/webm" /> : null}<source src={petLuxoFullVideoLoaded ? "/embarpet-petluxo-baeta-alpargata.mp4" : "/embarpet-petluxo-preview-5s.mp4"} type="video/mp4" /></video><button type="button" className="ep-home-luxury__sound" onClick={() => { if (!petLuxoFullVideoLoaded) { setPetLuxoFullVideoLoaded(true); setPetLuxoUnmuted(true); return; } setPetLuxoUnmuted((current) => !current); }}>{petLuxoUnmuted ? <VolumeX size={15} /> : <Volume2 size={15} />}{petLuxoUnmuted ? "Silenciar" : "Ativar som"}</button></div><div className="ep-home-luxury__content"><p className="ep-eyebrow">Acompanhamento especializado</p><h2 className="ep-title-lg">Um consultor especializado acompanha seu pet até você.</h2><p className="ep-copy">PetLuxo é um acompanhamento dedicado para jornadas que pedem presença e coordenação ainda mais próximas. Um consultor especializado conduz o pet com atenção aos marcos definidos até o encontro com a família.</p><div className="ep-home-luxury__list"><span><i>01</i><Crown size={17} /><b>Planejamento individual</b><small>Uma leitura própria para a jornada da família.</small></span><span><i>02</i><HeartHandshake size={17} /><b>Presença especializada</b><small>Um consultor acompanha o pet nos marcos combinados.</small></span><span><i>03</i><ShieldCheck size={17} /><b>Coordenação até o encontro</b><small>Cuidado contínuo até a entrega planejada.</small></span></div><div className="ep-home-luxury__actions"><Button variant="secondary" icon="arrow" onClick={() => document.getElementById("analise")?.scrollIntoView({ behavior:"smooth" })}>Avaliar PetLuxo</Button></div></div></div></section>

    <InternationalTransfer subtitle="Comece pelo destino" title="Comece por onde vocês vão chegar." description="Regras, prazos e processos variam conforme o destino. Selecione uma rota prioritária ou conte outra: levamos essa informação para a análise inicial." regions={regions} onCountrySelect={(country) => startFromDestination(country.name)} />

    <section className="ep-home-authority"><div className="ep-container ep-home-authority__grid"><div className="ep-home-authority__mosaic" aria-label="Momentos reais de embarques internacionais acompanhados pela Embarpet"><figure className="ep-home-authority__tile ep-home-authority__tile--main"><img src={images.documents} alt="Pet em viagem internacional diante de um destino icônico" /></figure><figure className="ep-home-authority__tile ep-home-authority__tile--talles"><img src="/embarpet-mosaico-cabine.jpeg" alt="Pet em cabine durante uma viagem internacional" /></figure><figure className="ep-home-authority__tile ep-home-authority__tile--leandro"><img src="/embarpet-mosaico-cuidado.jpg" alt="Tutor com pet em momento de cuidado" /></figure><figure className="ep-home-authority__tile ep-home-authority__tile--renato"><img src="/embarpet-mosaico-familia.jpg" alt="Família e pet aproveitando o destino" /></figure><figure className="ep-home-authority__tile ep-home-authority__tile--luxury"><img src="/embarpet-mosaico-encontro.jpg" alt="Tutora com pet em momento de encontro" /></figure></div><div className="ep-home-authority__content"><p className="ep-eyebrow">Experiência comprovada</p><h2 className="ep-title-lg">Não é só saber a regra. É saber <em>o que ela muda</em> na viagem de vocês.</h2><p className="ep-copy">Cada rota combina requisitos, prazo, documentação, companhia aérea e perfil do pet. Essa leitura integrada transforma informação em um plano possível.</p><div className="ep-home-authority__proof"><div><strong>+2.000</strong><span>embarques<br />analisados</span></div><div><img src="/logo-ipata.png" alt="IPATA" /><span>credenciada</span></div><div><img src="/logo-iata.png" alt="IATA" /><span>credenciada</span></div></div><a className="ep-home-authority__story-cta" href="/equipe-e-credenciais"><span>Conheça nossa história</span><ArrowRight size={18} aria-hidden="true" /></a></div></div></section>

    <section className="ep-section ep-container ep-home-faq" id="faq"><div><SectionHeading eyebrow="Dúvidas frequentes" title="Perguntas frequentes sobre transporte aéreo de pets." copy="Respostas claras para os pontos que mais geram dúvidas antes de uma viagem internacional com animal de estimação." /></div><div className="ds-faq"><FAQItem question="Como transportar meu animal de estimação em avião?">O transporte aéreo de animais começa pela análise de origem, destino, prazo, espécie, porte e regras da companhia aérea. Com isso, avaliamos a modalidade possível — cabine, bagagem acompanhada ou carga viva — e o planejamento da documentação.</FAQItem><FAQItem question="O deck inferior do avião é confortável para pets?">Quando a modalidade é bagagem acompanhada ou carga viva, o pet viaja em compartimento apropriado da aeronave. As condições dependem da companhia aérea, rota, caixa de transporte e critérios operacionais; por isso cada embarque precisa ser avaliado individualmente.</FAQItem><FAQItem question="Alguém viaja com meu animal no deck inferior?">O pet não viaja acompanhado por uma pessoa dentro do compartimento de transporte. A operação é conduzida pela companhia aérea e pelas equipes de solo; quando aplicável, o tutor segue no mesmo voo e recebe orientação sobre cada etapa do embarque.</FAQItem><FAQItem question="Animais braquicefálicos podem viajar de avião?">Cães e gatos braquicefálicos podem ter restrições específicas por causa de características respiratórias. A possibilidade de transporte aéreo depende da raça, condição veterinária, companhia aérea, rota e modalidade disponível no momento da viagem.</FAQItem><FAQItem question="O transporte aéreo de animais é seguro?">O transporte de pets por avião segue processos, normas e cuidados próprios, mas a segurança depende de uma decisão bem planejada: rota adequada, documentação, caixa correta, condição do animal e regras atualizadas da companhia aérea e do destino.</FAQItem><FAQItem question="Como preparar meu animal para o transporte aéreo?">A preparação para viagem de pet inclui adaptação à caixa de transporte, consulta veterinária quando indicada, documentação, rotina de alimentação e orientações para o dia do voo. O plano correto varia conforme o perfil do animal e a rota internacional.</FAQItem><FAQItem question="O que é CVI para viagem internacional com pet?">O CVI, ou Certificado Veterinário Internacional, é um documento oficial usado no processo de saída do Brasil com animal de estimação. Os requisitos e a emissão seguem o fluxo da autoridade competente e as exigências do país de destino.</FAQItem><FAQItem question="Como escolher a caixa de transporte ideal para meu pet?">A caixa de transporte para avião precisa respeitar as medidas do pet, ventilação, material, modalidade de embarque e regras da companhia aérea. Uma caixa adequada permite que o animal fique em posição natural e atende às especificações da viagem.</FAQItem></div></section>
    <ScrollFlyIn className="ep-final-fly-in" imageUrl="/embarpet-cta-plane-top.webp" imageAlt="Avião Embarpet cruzando a tela"><div className="mx-auto max-w-3xl px-4 text-center"><div className="ep-final-impact" aria-label="Mais de dois mil embarques analisados"><span className="ep-final-impact__avatars" aria-hidden="true"><i /><i /><i /><i /></span><strong>+2.000</strong><small>embarques<br />analisados</small></div><h2 className="mt-2 text-5xl font-bold leading-tight text-white md:text-7xl">Vamos começar a desenhar a viagem do seu pet?</h2><p className="mx-auto mt-6 max-w-xl text-sm leading-relaxed text-white/75">Conte o destino e os dados do seu pet. Com isso, nossa equipe começa a analisar o processo da viagem.</p><button type="button" onClick={() => document.getElementById("analise")?.scrollIntoView({ behavior:"smooth" })} className="ep-button ep-button--primary mt-8">Iniciar minha análise</button></div></ScrollFlyIn>
  </main><SiteFooter logoSrc="/logo-embarpet-dark.png" groups={[
    { title:"Planeje a viagem", links:[{ label:"Como funciona", href:"#como-funciona" },{ label:"Modalidades", href:"#modalidades" },{ label:"Destinos", href:"#destinos" }] },
    { title:"Conteúdo", links:[{ label:"Guias para viagem", href:"#guias" },{ label:"Histórias reais", href:"#historias" },{ label:"Perguntas frequentes", href:"#faq" }] },
    { title:"Embarpet", links:[{ label:"Sobre nós", href:"#sobre" },{ label:"Fale com a equipe", href:"#analise" },{ label:"Privacidade", href:"#privacidade" }] },
  ]} /><WhatsAppFloat context={leadContext} onStart={(context) => setMessage("Entrada WhatsApp preparada para " + (context.destination || "sua rota") + ".")} /></>;
}
